services:
  db:
    image: mysql:8.0
    container_name: Ecommercedb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: EcommerceDB  # ✅ opravené
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
