version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: kasino-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: kasino
      MYSQL_USER: kasino_user
      MYSQL_PASSWORD: kasino_pass
    ports:
      - "3306:3306"
    volumes:
      - kasino_data:/var/lib/mysql

volumes:
  kasino_data:
